### ISSUE TITLE
Hoard! new version v0.9.9 stopped Satisfactory from Loading today on 21st March 2020

### ISSUE THREAD

**Issue by SatisfactoryBug** [dudeamax99/Toilet-Paper-Mod#1]
Hoard! new version v0.9.9 stopped Satisfactory from Loading today on 21st March 2020

Also at Mod Loader show v0.9.9.1 when click Update is not working and there a missing Uninstall TAB which i cant Uninstall and I had to Delete all MODs and do it again excpet the Hoard! Loading Satisfactory all MODs working EXCEPT Hoard! that i wont install as it a BUG

It all ok now with ur update Hoard! v0.1.1

**Comment by rosegayming** [comment]
Fixed in 0.1.1
