### ISSUE TITLE
Off Topic complaining

### ISSUE THREAD

**Issue by LokeYourC3PH** [dudeamax99/Toilet-Paper-Mod#2]
Why did you make this mod? I mean you apparently can make mods, so why waste time on something like this? I have never criticized what type of mod a mod developer has made in their entire life before, but this just seems shitty. The world is currently in a bad situation, and I honestly don't think in any way that this mod or idea is in any way whatsoever funny. And you have talent so you could have done something so much better you know, but you make a mod about Toilet Paper that only stupid people hoard. I have dark humour as well, but I honestly cannot and will never understand why you made this, or decided to publish it that is. Sorry not sorry.

**Comment by rosegayming** [comment]
@LokeYourLord Cause some people suggested it, it's my first mod and I thought it could be a cool way to learn.

**Comment by LokeYourC3PH** [comment]
Alright I see, I guess it makes sense for learning purposes.

**Comment by rosegayming** [comment]
Also, even if it wasn’t as a learning experience, what’s wrong with someone making something they like?
